### ISSUE TITLE
add support for GIMP 2.10

### ISSUE THREAD

**Issue by wanted0** [akkana/gimp-plugins#15]
When starting the Saver plugin in GIMP 2.10.8 (Ubuntu) I get:
```
Querying plug-in: '/home/wanted/.config/GIMP/2.10/plug-ins/saver.py'
gimp: LibGimpBase-WARNING: gimp: gimp_wire_read(): error
Terminating plug-in: '/home/wanted/.config/GIMP/2.10/plug-ins/saver.py'
```
and the plugin is not working.

**Comment by imurray** [comment]
The plugin works for me using gimp 2.10.18-1 on Ubuntu 20.04, but only after installing `gimp-python`, which isn't available in the repositories any more. Upgrading gimp might be your answer.

To get gimp-python support (so the script can import gimpfu), you'll need python2.7 and some dependencies. I already had `python2.7` installed but needed to install `python-cairo` and `python-gobject-2`. Then the remaining dependencies I had to install from a previous Ubuntu version:

    wget http://mirrors.kernel.org/ubuntu/pool/universe/p/pygtk/python-gtk2_2.24.0-6_amd64.deb
    sudo dpkg -i python-gtk2_2.24.0-6_amd64.deb
    wget http://mirrors.kernel.org/ubuntu/pool/universe/g/gimp/gimp-python_2.10.8-2_amd64.deb
    sudo dpkg -i gimp-python_2.10.8-2_amd64.deb

It's possibly you'll need to install other packages I already had too. `dpkg` will tell you.

It seems that gimp is moving over to using python3, but that Ubuntu didn't get a version with python3 support into their release in time. So, at some point `saver.py` will need porting to python3...

**Comment by imurray** [comment]
Those who've upgraded to Ubuntu 22.04 (LTS), will have found that getting `gimp-python` installed as a system package is now more difficult.

However, `saver.py` does still work with GIMP 2.10 if installed following the [official instructions to download GIMP](https://www.gimp.org/downloads/), which use flatpak.

```
# To install and run the latest stable version of GIMP (2.10 at time of writing) on GNU/Linux:
sudo apt install flatpak
flatpak install https://flathub.org/repo/appstream/org.gimp.GIMP.flatpakref
flatpak run org.gimp.GIMP//stable 
```

The `saver.py` plugin goes in one of these directories (the flatpak uses the first one if you had it, or creates the second one if not):
```
    ~/.config/GIMP/2.10/plug-ins
    ~/.var/app/org.gimp.GIMP/config/GIMP/2.10/plug-ins
```

GIMP 2.10 is still using python2, but the flatpak comes with its own python2 and just works. The development version of GIMP (2.99) uses python3, and has made breaking changes to its plugin API, so `saver.py` doesn't currently work with that.

**Comment by akkana** [comment]
Sorry, somehow I missed seeing notifications for this issue, until the latest one. Sorry about that!

I'm not convinced the `gimp: gimp_wire_read(): error `means anything. I see that all the time, even from built-in plug-ins, so it's not just saver.

On Debian I'm using the flatpak version, like imurray describes. However, under 2.10.30 from flatpak, saver didn't seem to work: it called up its dialog, but when the time came to call pdb.gimp_file_save, it just failed silently, so it would look like it had saved, but no file would be there. I don't know what was going on, and kept meaning to investigate, but when I finally got time, I noticed I was a couple GIMP versions behind, so I updated (using `flatpak update`) to the latest gimp-2.10.32 flatpak, and the problem was gone, saver seems to be working fine again.

For 2.99, it's not just a change to Python 3; the whole plug-in API changes, so every plug-in, in any language, has to be completely rewritten. I've been waiting for the API to stabilize a bit more before trying to port my plug-ins, but I definitely will port saver well before it's time for GIMP 3.0.

I'm going to close this because saver seems to work for me now under 2.10.32. But if anyone still sees it failing under .32 or later, please reopen this (or comment here and I'll reopen).

**Comment by imurray** [comment]
Just a note to say thank you very much for saver! For my common use case of opening and making quick destructive edits to many files in simple formats, it turns GIMP from unusable to usable. (Understood re: the new API.)
