### ISSUE TITLE
Hide native save / save as / export / export as

### ISSUE THREAD

**Issue by Smile4ever** [akkana/gimp-plugins#7]
I would like to hide the native save and export options in the File menu. Otherwise the menu becomes a bit of a mess.

**Comment by akkana** [comment]
Sorry, I don't know how to remove existing menu entries, or if there even is a way. You might try asking on the gimp-developer mailing list, https://mail.gnome.org/mailman/listinfo/gimp-developer-list
I wouldn't want to make that a standard part of saver or save-export-clean; although I certainly understand your complaint and certainly agree that ideally a user should be able to choose to do that. It could be a separate plug-in, maybe, so the standard menu items only get hidden for people who want to do that.

I'll close this since I'm not sure it's possible in gimp, but if you find out I'm wrong, reopen it (and let me know what you found out about how it's done) and I'd be happy to work with you on writing a plug-in to hide those menus.

**Comment by Smile4ever** [comment]
Hi. I found a way. You need to edit /usr/share/gimp/2.0/menus and comment out a few lines so that it becomes:
      <separator/>
      <placeholder name="Save">
        
      </placeholder>
      <menuitem action="file-revert"/>
      <separator/>
     
      <menuitem action="file-create-template"/>
There are no changes required in the Saver plug-in code.

**Comment by akkana** [comment]
Excellent! That's easier than I expected. I've added a link to your instructions (the one you posted on gimp-developer list) on my web page for the Saver plug-in (and added a link to that page in the github README, which I should have had before).
